  extends: "eslint-config-funkmonkey"
  env:
    node: true
  parser: "typescript-eslint-parser"
  rules:
    no-undef: off
    no-unused-vars: off
    import/extensions:
      - error
      - always
      -
        js: never
        mjs: never
        jsx: never
        ts: never

  settings:
    import/resolver:
      node:
        extensions:
        - ".js"
        - ".jsx"
        - ".ts"
    import/extensions:
        - ".js"
        - ".jsx"
        - ".ts"
